name: ismir2017-deepsalience
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.7
  - pip
  - pip:
      - absl-py==2.2.1
      - astunparse==1.6.3
      - audioread==3.0.1
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - decorator==5.2.1
      - flatbuffers==25.2.10
      - gast==0.6.0
      - google-api-core==2.24.2
      - google-api-python-client==2.166.0
      - google-auth==2.38.0
      - google-auth-httplib2==0.2.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.69.2
      - grpcio==1.71.0
      - h5py==3.13.0
      - httplib2==0.22.0
      - idna==3.10
      - joblib==1.4.2
      - keras==3.9.1
      - lazy_loader==0.4
      - libclang==18.1.1
      - librosa==0.11.0
      - llvmlite==0.44.0
      - Markdown==3.7
      - markdown-it-py==3.0.0
      - MarkupSafe==3.0.2
      - mdurl==0.1.2
      - medleydb==1.3.4
      - mir_eval==0.8.2
      - ml_dtypes==0.5.1
      - msgpack==1.1.0
      - namex==0.0.8
      - numba==0.61.0
      - numpy==2.1.3
      - oauth2client==4.1.3
      - opt_einsum==3.4.0
      - optree==0.14.1
      - packaging==24.2
      - pescador==3.0.0
      - platformdirs==4.3.7
      - pooch==1.8.2
      - proto-plus==1.26.1
      - protobuf==5.29.4
      - pyasn1==0.6.1
      - pyasn1_modules==0.4.2
      - pycparser==2.22
      - PyDrive==1.3.1
      - Pygments==2.19.1
      - pyparsing==3.2.3
      - PyYAML==6.0.2
      - pyzmq==26.3.0
      - requests==2.32.3
      - rich==14.0.0
      - rsa==4.9
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - setuptools==65.5.0
      - six==1.17.0
      - soundfile==0.13.1
      - sox==1.5.0
      - soxr==0.5.0.post1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.0.0
      - threadpoolctl==3.6.0
      - typing_extensions==4.13.0
      - uritemplate==4.1.1
      - urllib3==2.3.0
      - Werkzeug==3.1.3
      - wheel==0.45.1
      - wrapt==1.17.2